import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import UpperNav from './ui/navigation/uppernav'
import LowerNav from './ui/navigation/lowernav'
import Footer from './ui/footer/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
    <body className={inter.className}>
      <UpperNav/>
      <LowerNav/>
        {children}
      <Footer/>
    </body>
      
    </html>
  )
}
